---
# handlers file for roles/prometheus
- name: restart_prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: reload_prometheus
  uri:
    url: https://localhost:5050/-/reload
    method: POST
    status_code: 200
