---
# tasks file for consul

- name: install utils
  apt:
    name: 
      - curl
      - wget
      - net-tools
      - unzip
    update_cache: yes
    cache_valid_time: 3600
    state: present

- name: check if consul exists
  stat:
    path: /usr/local/bin/consul
  register: consul_exist

- name: download consul
  unarchive: 
    src: https://releases.hashicorp.com/consul/1.11.3/consul_1.11.3_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
  when: consul_exist.stat.exists == False